---
name: PHP Aula 5 - Uploads e Manipulação de Arquivos
locale: pt
type: learning
beta: false
teacher_info: ''
language: php
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
private: false
